### ISSUE TITLE
[Create Journey] Create a Ride Page

### ISSUE THREAD

**Issue by OlenaBobalo** [ita-social-projects/Car-Front-End#58]
**As a** Driver **I want to** add trip points and see recommended route on the screen **so that** I can verify that route is chosen correctly and confirm it.

**Mockups**
<img width="367" alt="US_2_CreateJourney_1" src="https://user-images.githubusercontent.com/62544149/115559140-17b19f00-a2bc-11eb-9206-22241314a77e.png">
<img width="128" alt="US_2_CreateJourney_2" src="https://user-images.githubusercontent.com/62544149/116235387-7799c100-a766-11eb-8f6f-6c159268fa79.png">

### Acceptance Criteria
1. User accesses the page by pushing Ride Homepage (US[#24](https://github.com/ita-social-projects/Car-Back-End/issues/24)).
2. WHEN User pushes at Ellipsis menu "...", system shall open More options panel with 3 options: Add stop (US[#54](https://github.com/ita-social-projects/Car-Back-End/issues/54)), Schedule This Journey (US[#392](https://github.com/ita-social-projects/Car-Back-End/issues/392)), Change Preferences (US[#21](https://github.com/ita-social-projects/Car-Back-End/issues/21)).
3. For selecting date and time User shall push Departure Time edit box (US[#2](https://github.com/ita-social-projects/Car-Back-End/issues/2)).
4. Ride Type shall consist of two buttons: Own Car and Taxi.
4.1. IF User chooses Own Car option, the system shall create a dropdown with a list of cars available in their My Car profile (US[#20](https://github.com/ita-social-projects/Car-Back-End/issues/20)).
4.1.1. System shall show the car list in the same sequence as they are placed at the My Car profile.
4.2. IF User chooses Taxi option, the system shall mark in the DB base, that trip will be executed at the taxi.
5. 'Passengers' dropdown shall contain options 1, 2, 3, 4 seats.
5.1. Option "4" shall be chosen by default.
6. User shall choose Fee mode pushing button Free or Paid.
6.1. Button Free shall be active by default.
7. Comments box shall let to input short messages - up to 100 symbols.
8. WHEN User pushes Publish button, the system shall save published Ride into Rides DB.

### Assumptions & Constraints
1. User can scroll up and down the page.

**Epic link**
Epic ita-social-projects/Car-Back-End#67 

**Labels to be added**
"User story" ("story"), Priority ("pri: ")

### Tasks 
1. - [ ] sample task.

**Comment by Vladyslava95** [comment]
@OlenaBobalo Why this US is closed?

**Comment by OlenaBobalo** [comment]
> @OlenaBobalo Why this US is closed?

@Vladyslava95 'cos US 58 (FE) is a clone of 54 (BE)

**Comment by OlenaBobalo** [comment]
Reopen due to unavailability of these options in App working version
