### ISSUE TITLE
[Publish a Ride] Must be three passenger by default in 'Add a ride' when user choose taxi 

### ISSUE THREAD

**Issue by Marta-Yasnuska** [ita-social-projects/Car-Front-End#673]
Environment: Android Samsung Galaxy A 10s
Reproducible: always
Build found: v1.0.397

Preconditions:
1. 'Car' app is open
2. User logged in
3. The main page is open

Steps to reproduce:
1. Go to 'Add a ride'
2. Choose 'From' and 'To' values 
3. Press 'Save' button

Actual result: 
On 'Publish a ride' page when user choose 'Ride type - 'Taxi', seats in 'Passenger' is four by default.

Expected result:
On 'Publish a ride' page when user choose 'Ride type - 'Taxi', maximum number in 'Passenger' seat menu must be three, and three seats are displayed by default.

User story and test case links:
User story #58 

![зображення_viber_2021-11-05_20-21-06-138](https://user-images.githubusercontent.com/91321998/140562381-9f87a776-f6e0-4ca6-9990-b94d8473c3e5.jpg)

**Comment by Sydir** [comment]
fixed in v1.0.413
