### ISSUE TITLE
[Publish a ride] User can't write comments in 'Publish a ride' when he create a new ride

### ISSUE THREAD

**Issue by Marta-Yasnuska** [ita-social-projects/Car-Front-End#682]
Environment: Android Samsung Galaxy A 10s
Reproducible:  always
Build found: v1.0.408.apk

Preconditions:
1. 'Car' app is open
2. User is logged
3. The Main page open 

Steps to reproduce:
1. Go to 'Add a ride'
2. Choose 'From' (e.g. Katowice, Poland'),  press on  'To' (e.g.  Lviv, Lviv Oblast, Ukraine) press 'Confirm' button
3. In 'Publish a ride' scroll down to 'Comments' tap some text in text box.

Actual result:
In 'Comments' user can't write text

Expected result:
In 'Comments' user can write text in the text box and can 'Publish' it.

https://user-images.githubusercontent.com/91321998/140740164-afc20ec0-9488-4554-b4ad-f14a5c836397.mp4

Labels to be added
"Bug", Priority ("pri: medium "), Type ("Functional")

**Comment by MedytskyiOleksandr** [comment]
Same as #ita-social-projects/Car-Back-End/issues/848
